version: '3.8'
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user -d db"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      JWT_SECRET: 
      JWT_EXPIRATION: 
      file_upload_dir: /app/uploads
      file_upload_directory: /app/uploads
      SPRING_PROFILES_ACTIVE: dev

    volumes:
      - upload_volume:/app/uploads
    depends_on:
      - database
    healthcheck:
        test: ["CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
       - "3000:80"
    environment: {}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db_data:
  upload_volume:
