export const UnitType = {
	WARD: { displayName: "Ward" },
	GENERAL_MEDICAL: { displayName: "General Medical" },
	GENERAL_SURGICAL: { displayName: "General Surgical" },
	PEDIATRIC: { displayName: "Pediatric" },
	OBSTETRICS_GYNECOLOGY: { displayName: "Obstetrics & Gynecology" },
	ORTHOPEDIC: { displayName: "Orthopedic" },
	ICU: { displayName: "Intensive Care Unit" },
	CCU: { displayName: "Cardiac Care Unit" },
	NICU: { displayName: "Neonatal ICU" },
	ONCOLOGY: { displayName: "Oncology" },
	DIALYSIS: { displayName: "Dialysis" },
	PSYCHIATRIC: { displayName: "Psychiatric" },
	NEUROLOGY: { displayName: "Neurology" },
	PULMONARY: { displayName: "Pulmonary" },
	GASTROENTEROLOGY: { displayName: "Gastroenterology" },
	OPHTHALMOLOGY: { displayName: "Ophthalmology" },
	ENT: { displayName: "ENT" },
	DERMATOLOGY: { displayName: "Dermatology" },
	REHABILITATION: { displayName: "Rehabilitation" },
	INFECTIOUS_DISEASE: { displayName: "Infectious Disease" },
	EMERGENCY: { displayName: "Emergency" },
	OPERATING_ROOM: { displayName: "Operating Room" },
	LABORATORY: { displayName: "Laboratory" },
	RADIOLOGY: { displayName: "Radiology" },
	PHARMACY: { displayName: "Pharmacy" },
	OUTPATIENT: { displayName: "Outpatient Clinic" },
};
