// PdfGenerator.js
import React from "react"; // Core React library
import html2pdf from "html2pdf.js"; // Library for converting HTML to PDF
import moment from "moment"; // Library for date/time formatting
import QRCode from "qrcode"; // Library for generating QR codes
import { notification } from "antd"; // Ant Design's notification component
import { usePatientDetailStore } from "../../services/patientDetail.service"; // <--- ADDED

const PdfGenerator = ({ type, mode, data, columns, fileNamePrefix, children, labTests }) => {
	// --- (Rest of your utility functions and common styles) ---
	const toBase64 = async (url) => {
		try {
			const response = await fetch(url);
			if (!response.ok) {
				throw new Error(`HTTP error! status: ${response.status}`);
			}
			const blob = await response.blob();
			return new Promise((resolve, reject) => {
				const reader = new FileReader();
				reader.onloadend = () => resolve(reader.result);
				reader.onerror = reject;
				reader.readAsDataURL(blob);
			});
		} catch (error) {
			console.error("Error converting image to Base64:", error);
			return null;
		}
	};

	// --- Optimized Table Generation ---
	const generateTableHTML = (columns, dataSource) => {
		if (!columns || columns.length === 0 || !dataSource || dataSource.length === 0) {
			return "<p>No data available.</p>";
		}

		const filteredColumns = columns.filter((col) => col.dataIndex);

		const tableHeader = filteredColumns
			.map(
				(col) => `
        <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #2d3748;">
          ${col.title}
        </th>`
			)
			.join("");

		const tableRows = dataSource
			.map(
				(row, rowIndex) => `
        <tr style="background-color: ${rowIndex % 2 === 1 ? "#f8fafc" : "#fff"};">
          ${filteredColumns
				.map((col) => {
					let cellValue = row[col.dataIndex];
					if (col.dataIndex.toLowerCase().includes("date") && cellValue) {
						cellValue = moment(cellValue).format("YYYY-MM-DD HH:mm");
					}
					return `
              <td style="padding: 3px 4px; border-bottom: 1px solid #e2e8f0; color: #4a5568;">
                ${cellValue || "—"}
              </td>`;
				})
				.join("")}
        </tr>`
			)
			.join("");

		return `
      <table style="width: 100%; table-layout: fixed; border-collapse: collapse; border-spacing: 0; margin-top: 0px; font-size: 7pt; background-color: #fff; border-radius: 0px; overflow: hidden; border: 1px solid #e2e8f0;">
        <thead>
          <tr style="background: linear-gradient(to right, #f8f9fa, #ffffff);">${tableHeader}</tr>
        </thead>
        <tbody>${tableRows}</tbody>
      </table>`;
	};

	// --- Common PDF Styles ---
	const commonPdfStyles = `
    padding: 0px;
    font-family: system-ui, -apple-system, sans-serif;
    max-width: 100%;
    margin: 0px auto;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
    background: linear-gradient(to bottom, #ffffff 0%, #f8f9fa 100%);
    border-radius: 0px;
    box-shadow: none;
    @media print {
      background: none;
      box-shadow: none;
            margin: 0 !important;
      padding: 0 !important;
      size: auto;
    }
  `;

	const commonHeaderStyles = `
    text-align: center;
    margin-bottom: 0.5rem;
    padding: 0.5rem;
    background: linear-gradient(135deg, #2c3e50 0%, #3498db 100%);
    border-radius: 0px;
    color: white;
    @media print {
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
      margin: 0 !important;
      padding: 0 !important;
    }
  `;

	const commonFooterStyles = `
    margin-top: 0.25rem;
    padding: 0.25rem;
    background: #f8f9fa;
    border-radius: 0px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 5pt;
    color: #64748b;
  `;

	const generateCommonHeader = (title, documentId = null) => `
    <div style="${commonHeaderStyles}">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.25rem;">
        <div style="text-align: left; padding-left: 0.25rem;">
          <h1 style="margin: 0; font-size: 14pt; font-weight: 600;">Hospital Name</h1>
          <p style="margin: 1px 0; font-size: 7pt; opacity: 0.8;">${moment().format("dddd, MMMM D, YYYY")}</p>
        </div>
        ${
			documentId
				? `<div style="background: rgba(255,255,255,0.1); padding: 3px 6px; border-radius: 3px; font-size: 6pt;">Document ID: ${documentId}</div>`
				: ""
		}
      </div>
      <h2 style="margin: 0; font-size: 11pt; font-weight: 400;">${title}</h2>
    </div>`;

	const generateCommonFooter = () => `
    <div style="${commonFooterStyles}">
      <div>
        <p style="margin: 0;">Generated by Hospital System v2.0</p>
        <p style="margin: 0px 0;">Document ID: GEN-${Date.now().toString(36)}</p>
      </div>
      <div style="text-align: right;">
        <p style="margin: 0;">Generated on ${moment().format("YYYY-MM-DD HH:mm")}</p>
        <p style="margin: 0px 0;">Page 1 of 1</p>
      </div>
    </div>`;

	// --- Specific PDF Generation Functions ---
	// Admissions
	const generateAdmissionPdf = (admission) => {
		if (!admission) return null;
		const documentId = `ADM-${admission.id}`;
		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Admission Details 📝", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Admission Date:</strong> ${admission.admissionDate ? moment(admission.admissionDate).format("YYYY-MM-DD HH:mm") : "N/A"}</p>
          <p><strong>Discharge Date:</strong> ${admission.dischargeDate ? moment(admission.dischargeDate).format("YYYY-MM-DD HH:mm") : "Open"}</p>
          <p><strong>Bed ID: 🛏️</strong> ${admission.bedId || "N/A"}</p>
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateAdmissionTablePdf = (admissions, columns) => {
		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Admissions 📝")}
        ${generateTableHTML(columns, admissions)}
        ${generateCommonFooter()}
      </div>`;
	};

	// Appointments
	const generateAppointmentPdf = (appointment) => {
		if (!appointment) return null;
		const documentId = `APP-${appointment.id}`;
		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Appointment Details 📅", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Appointment Date:</strong> ${
				appointment.appointmentDate ? moment(appointment.appointmentDate).format("YYYY-MM-DD HH:mm") : "N/A"
			}</p>
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateAppointmentTablePdf = (appointments, columns) => {
		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Appointments 📅")}
        ${generateTableHTML(columns, appointments)}
        ${generateCommonFooter()}
      </div>`;
	};

	// Billing
	const generateBillingPdf = async (billingData) => {
		if (!billingData || !billingData.bill) {
			notification.error({ message: "Error", description: "No billing content available to export." });
			return null;
		}
		const documentId = `BILL-${billingData.id}`;

		const div = document.createElement("div");
		div.innerHTML = billingData.bill;

		// --- ADDED STYLING ---
		// Apply styles directly to the div containing the bill HTML.  This is the most targeted approach.
		div.style.fontSize = "7pt"; // Reduced font size
		div.style.padding = "0.25rem"; // Reduced padding
		div.style.lineHeight = "1.2"; // Tighter line spacing

		//If there are tables inside:
		const tables = div.querySelectorAll("table");
		tables.forEach((table) => {
			table.style.fontSize = "6pt"; // Further reduce font size inside tables
			const cells = table.querySelectorAll("td, th");
			cells.forEach((cell) => {
				cell.style.padding = "2px"; // Reduce cell padding
			});
		});
		// --- END ADDED STYLING ---

		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Billing Details 💰", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Billing Date:</strong> ${billingData.billDate ? moment(billingData.billDate).format("YYYY-MM-DD HH:mm") : "N/A"}</p>
          ${div.outerHTML}  
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateBillingTablePdf = (billings) => {
		if (!billings || billings.length === 0) {
			return "<p>No billing data available.</p>";
		}

		let combinedBillContent = "";
		for (const billing of billings) {
			const div = document.createElement("div");
			div.innerHTML = billing.bill; // Assuming 'bill' contains the HTML content

			// --- ADDED STYLING ---
			div.style.fontSize = "7pt";
			div.style.padding = "0.25rem";
			div.style.lineHeight = "1.2";

			//If there are tables inside:
			const tables = div.querySelectorAll("table");
			tables.forEach((table) => {
				table.style.fontSize = "6pt"; // Further reduce font size inside tables
				const cells = table.querySelectorAll("td, th");
				cells.forEach((cell) => {
					cell.style.padding = "2px"; // Reduce cell padding
				});
			});

			// --- END ADDED STYLING ---

			combinedBillContent += `
          <div style="padding: 0 0.5rem;">
            <h3 style="color: #444; margin-top: 20px;">Billing Details 💰 ${moment(billing.billDate).format("YYYY-MM-DD HH:mm")}</h3>
            ${div.outerHTML}
            <hr style="margin-top: 10px; margin-bottom: 10px;"/>
          </div>
      `;
		}

		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Billing History 💰")}
        ${combinedBillContent}
        ${generateCommonFooter()}
      </div>
    `;
	};
	// Assessments
	const generateAssessmentPdf = (assessment) => {
		if (!assessment) return null;
		const documentId = `ASSESS-${assessment.id}`;

		const tempDiv = document.createElement("div");
		tempDiv.innerHTML = assessment.notes;

		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Assessment Details 📋", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Assessment Date:</strong> ${
				assessment.assessmentDateTime ? moment(assessment.assessmentDateTime).format("YYYY-MM-DD HH:mm") : "N/A"
			}</p>
          <h3>Notes</h3>
          <div>${tempDiv.outerHTML}</div>
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateAssessmentTablePdf = (assessments) => {
		if (!assessments || assessments.length === 0) {
			return "<p>No assessment data available.</p>";
		}

		let combinedAssessmentContent = "";
		for (const assessment of assessments) {
			const tempDiv = document.createElement("div");
			tempDiv.innerHTML = assessment.notes;

			combinedAssessmentContent += `
          <div style="padding: 0 0.5rem; border-bottom: 1px solid #eee;">
            <h3 style="color: #444; margin-top: 20px;">Assessment Details 📋 - ${moment(assessment.assessmentDateTime).format(
				"YYYY-MM-DD HH:mm"
			)}</h3>
            <div>${tempDiv.outerHTML}</div>
          </div>
      `;
		}

		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Assessment History 📋")}
        ${combinedAssessmentContent}
        ${generateCommonFooter()}
      </div>
    `;
	};

	// Care Plans
	const generateCarePlanPdf = (carePlan) => {
		if (!carePlan) return null;
		const documentId = `CP-${carePlan.id}`;

		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Care Plan Details 🩺", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Plan Date:</strong> ${carePlan.planDate ? moment(carePlan.planDate).format("YYYY-MM-DD HH:mm") : "N/A"}</p>
          <p><strong>Goal: 🎯</strong> ${carePlan.goal || "N/A"}</p>
          <p><strong>Interventions: 🛠️</strong> ${carePlan.interventions || "N/A"}</p>
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateCarePlanTablePdf = (carePlans, columns) => {
		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Care Plans 🩺")}
        ${generateTableHTML(columns, carePlans)}
        ${generateCommonFooter()}
      </div>`;
	};

	// Prescriptions
	// Prescriptions
	const generatePrescriptionPdf = (prescription) => {
		if (!prescription) return null;
		const documentId = `PRESC-${prescription.id}`;

		const medicationsList = (prescription.prescribedMedications || [])
			.map(
				(med) => `
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 4px; width: 25%;">${med.medicationName || "—"}</td>
                <td style="padding: 4px; width: 25%;">${med.dosage || "—"}</td>
                <td style="padding: 4px; width: 20%;">${med.route || "—"}</td>
                <td style="padding: 4px; width: 15%;">${med.amount || "—"}</td>
                <td style="padding: 4px; width: 15%;">${med.expired ? "✅" : "❌"}</td>
            </tr>`
			)
			.join("");

		return `
    <div style="${commonPdfStyles}">
        ${generateCommonHeader("Prescription Details 💊", documentId)}
        <div style="padding: 0 0.5rem;">
            <p><strong>Prescription Date: 📅</strong> ${
				prescription.prescriptionDate ? moment(prescription.prescriptionDate).format("YYYY-MM-DD HH:mm") : "N/A"
			}</p>
            <p><strong>Expiration Date: ⏳</strong> ${
				prescription.expirationDate ? moment(prescription.expirationDate).format("YYYY-MM-DD") : "N/A"
			}</p>
            <p><strong>Patient Name: 👤</strong> ${prescription.patientName || "N/A"}</p>
            <p><strong>Note: 📝</strong> ${prescription.note || "N/A"}</p>
            
            <h3 style="margin-top: 1rem; font-size: 10pt;">Prescribed Medications 💊</h3>
            <table style="width: 100%; border-collapse: collapse; margin-top: 0.5rem;">
                <thead>
                    <tr style="background-color: #f0f0f0; border-bottom: 2px solid #ddd;">
                        <th style="padding: 4px; text-align: left; width: 25%;">Medication</th>
                        <th style="padding: 4px; text-align: left; width: 25%;">Dosage</th>
                        <th style="padding: 4px; text-align: left; width: 20%;">Route</th>
                        <th style="padding: 4px; text-align: left; width: 15%;">Amount</th>
                        <th style="padding: 4px; text-align: left; width: 15%;">Administered</th>
                    </tr>
                </thead>
                <tbody>
                    ${medicationsList}
                </tbody>
            </table>
        </div>
        ${generateCommonFooter()}
    </div>`;
	};

	const generatePrescriptionTablePdf = (prescriptions) => {
		if (!prescriptions || prescriptions.length === 0) {
			return "<p>No prescription data available.</p>";
		}

		let combinedPrescriptions = "";

		prescriptions.forEach((prescription, index) => {
			const medicationsList = (prescription.prescribedMedications || [])
				.map(
					(med) => `
                <tr style="border-bottom: 1px solid #eee;">
                    <td style="padding: 4px; width: 25%;">${med.medicationName || "—"}</td>
                    <td style="padding: 4px; width: 25%;">${med.dosage || "—"}</td>
                    <td style="padding: 4px; width: 20%;">${med.route || "—"}</td>
                    <td style="padding: 4px; width: 15%;">${med.amount || "—"}</td>
                    <td style="padding: 4px; width: 15%;">${med.expired ? "✅" : "❌"}</td>
                </tr>`
				)
				.join("");

			// Only add page-break-inside: avoid; to the div.  No forced breaks.
			const avoidPageBreakStyle = "page-break-inside: avoid;";

			combinedPrescriptions += `
            <div style="${avoidPageBreakStyle} margin-bottom: 20px; padding: 0.5rem; border: 1px solid #ddd; border-radius: 4px;">
                <h3 style="color: #333; margin-top:0;">Prescription (ID: ${prescription.id})</h3>
                <p><strong>Prescription Date: 📅</strong> ${
					prescription.prescriptionDate ? moment(prescription.prescriptionDate).format("YYYY-MM-DD HH:mm") : "N/A"
				}</p>
                <p><strong>Expiration Date: ⏳</strong> ${
					prescription.expirationDate ? moment(prescription.expirationDate).format("YYYY-MM-DD") : "N/A"
				}</p>
                <p><strong>Patient Name: 👤</strong> ${prescription.patientName || "N/A"}</p>
                <p><strong>Note: 📝</strong> ${prescription.note || "N/A"}</p>
                  <h4 style="margin-top: 1rem; font-size: 10pt;">Prescribed Medications 💊</h4>


                <table style="width: 100%; table-layout: fixed; border-collapse: collapse; border-spacing: 0; margin-top: 0px; font-size: 7pt; background-color: #fff; border-radius: 0px; overflow: hidden; border: 1px solid #e2e8f0;">
                    <thead>
                        <tr style="background: linear-gradient(to right, #f8f9fa, #ffffff);">
                            <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #2d3748; width: 25%;">Medication</th>
                            <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #2d3748;width: 25%;">Dosage</th>
                            <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #2d3748;width: 20%;">Route</th>
                            <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #2d3748;width: 15%;">Amount</th>
                            <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; color: #2d3748;width: 15%;">Administered</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${medicationsList}
                    </tbody>
                </table>
            </div>
        `;
		});
		// NO PAGE BREAK ADDED IN THE CONTAINER.
		return `
        <div style="${commonPdfStyles}">
            ${generateCommonHeader("Prescriptions 💊")}
            ${combinedPrescriptions}
            ${generateCommonFooter()}
        </div>
    `;
	};
	// Vital Signs
	const generateVitalSignPdf = (vitalSign) => {
		if (!vitalSign) return null;
		const documentId = `VS-${vitalSign.id}`;
		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Vital Sign Details 🌡️", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Record Date:</strong> ${vitalSign.timestamp ? moment(vitalSign.timestamp).format("YYYY-MM-DD HH:mm") : "N/A"}</p>
          <p><strong>Temperature: 🌡️</strong> ${vitalSign.temperature || "N/A"}</p>
          <p><strong>Heart Rate: ❤️</strong> ${vitalSign.heartRate || "N/A"}</p>
          <p><strong>Blood Pressure:</strong> ${vitalSign.bloodPressureSystolic}/${vitalSign.bloodPressureDiastolic}  </p>
          <p><strong>Respiratory Rate: 🫁</strong> ${vitalSign.respiratoryRate || "N/A"}</p>
          <p><strong>Oxygen Saturation: 💨</strong> ${vitalSign.oxygenSaturation || "N/A"}</p>
          <p><strong>Pain Level: 😖</strong> ${vitalSign.painLevel || "N/A"}</p>
          <p><strong>Height: 📏</strong> ${vitalSign.height ? `${vitalSign.height} ${vitalSign.heightUnit}` : "N/A"}</p>
          <p><strong>Weight: ⚖️</strong> ${vitalSign.weight ? `${vitalSign.weight} ${vitalSign.weightUnit}` : "N/A"}</p>
          <p><strong>Glucose: 🩸</strong> ${vitalSign.glucose ? `${vitalSign.glucose} ${vitalSign.glucoseUnit}` : "N/A"}</p>
          <p><strong>Posture: 🧍</strong> ${vitalSign.posture || "N/A"}</p>
          <p><strong>Capillary Refill Time: ⏱️</strong> ${vitalSign.capillaryRefillTime || "N/A"}</p>
          <p><strong>Method: ✍️</strong> ${vitalSign.method || "N/A"}</p>
          <p><strong>Notes: 📝</strong> ${vitalSign.notes || "N/A"}</p>
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateVitalSignTablePdf = (vitalSignsData) => {
		// Removed , columns
		const vitalSigns = vitalSignsData;

		if (!vitalSigns || vitalSigns.length === 0) {
			return '<p style="text-align: center; color: #666;">No vital signs data available.</p>';
		}

		const properties = [
			{ key: "timestamp", label: "Date", width: "11%", icon: "📅" },
			{ key: "temperature", label: "Temp", unit: "°C", width: "7%", icon: "🌡️" },
			{ key: "heartRate", label: "HR", unit: "bpm", width: "6%", icon: "💗" },
			{ key: "bloodPressureSystolic", label: "Sys", unit: "mmHg", width: "6%", icon: "⬆️" },
			{ key: "bloodPressureDiastolic", label: "Dia", unit: "mmHg", width: "6%", icon: "⬇️" },
			{ key: "respiratoryRate", label: "RR", unit: "/min", width: "6%", icon: "🫁" },
			{ key: "oxygenSaturation", label: "O2", unit: "%", width: "6%", icon: "⭐" },
			{ key: "painLevel", label: "Pain", width: "6%", icon: "😣" },
			{ key: "height", label: "Height", unitKey: "heightUnit", width: "7%", icon: "📏" },
			{ key: "weight", label: "Weight", unitKey: "weightUnit", width: "7%", icon: "⚖️" },
			{ key: "glucose", label: "Glucose", unitKey: "glucoseUnit", width: "8%", icon: "🔬" },
			{ key: "posture", label: "Posture", width: "6%", icon: "🧍" },
			{ key: "capillaryRefillTime", label: "Cap.Ref", width: "6%", icon: "⏱️" },
			{ key: "method", label: "Method", width: "6%", icon: "🔧" },
			{ key: "notes", label: "Notes", width: "6%", icon: "📝" },
		];

		const formatValue = (value, prop, vitalSign) => {
			if (value === null || value === undefined) return "—";
			if (prop.key === "timestamp") return moment(value).format("MM/DD HH:mm");
			if (prop.unitKey && vitalSign[prop.unitKey]) return `${value} ${vitalSign[prop.unitKey]}`;
			if (prop.unit) return `${value}${prop.unit}`;
			return value;
		};

		let tableHTML = `
    <div style="${commonPdfStyles}">
      ${generateCommonHeader("Vital Signs Report 📈")}

      <table style="width: 100%; table-layout: fixed; border-collapse: collapse; border-spacing: 0; margin-top: 0px; font-size: 7pt; background-color: #fff; border-radius: 0px; overflow: hidden; border: 1px solid #e2e8f0;">
        <thead>
          <tr style="background: linear-gradient(to right, #f8f9fa, #ffffff);">
  `;

		properties.forEach((prop) => {
			tableHTML += `
      <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; width: ${prop.width}; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: #2d3748;">
        <span style="display: inline-block; margin-right: 2px;">${prop.icon}</span>
        ${prop.label}
      </th>
    `;
		});

		tableHTML += `</tr></thead><tbody>`;

		vitalSigns.forEach((vitalSign, index) => {
			tableHTML += `
      <tr style="background-color: ${index % 2 === 1 ? "#f8fafc" : "#fff"}; transition: background-color 0.2s;">
    `;

			properties.forEach((prop) => {
				const value = formatValue(vitalSign[prop.key], prop, vitalSign);
				tableHTML += `
        <td style="padding: 3px 4px; border-bottom: 1px solid #e2e8f0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; line-height: 1.2; color: #4a5568;">${value}</td>
      `;
			});

			tableHTML += `</tr>`;
		});

		tableHTML += `
        </tbody>
      </table>
      ${generateCommonFooter()}
    </div>`;

		return tableHTML;
	};

	// Product Usage
	const generateProductUsagePdf = (productUsage) => {
		if (!productUsage) {
			return '<p style="text-align: center; color: #666;">No product usage data available.</p>';
		}
		const documentId = `PU-${productUsage.id}`;

		return `
    <div style="${commonPdfStyles}">
      ${generateCommonHeader("Product Usage Report 📦", documentId)}
        <div style="padding: 0 0.5rem;">
        <p><strong>Start Time: ⏳</strong> ${productUsage.startTime ? moment(productUsage.startTime).format("MM/DD HH:mm") : "—"}</p>
        <p><strong>End Time: ⌛</strong> ${productUsage.endTime ? moment(productUsage.endTime).format("MM/DD HH:mm") : "—"}</p>
        <p><strong>Product Name: 🏷️</strong> ${productUsage.productName || "—"}</p>
        <p><strong>Quantity: 🔢</strong> ${productUsage.quantity || "—"}</p>
        <p><strong>Price: 💲</strong> ${productUsage.price || "—"}</p>
      </div>
      ${generateCommonFooter()}
    </div>`;
	};

	const generateProductUsageTablePdf = (productUsages) => {
		// Removed , columns
		if (!productUsages || productUsages.length === 0) return '<p style="text-align: center; color: #666;">No product usage data available.</p>';

		const properties = [
			{ key: "startTime", label: "Start Time", width: "20%", icon: "⏱️" },
			{ key: "endTime", label: "End Time", width: "20%", icon: "⏱️" },
			{ key: "productName", label: "Product", width: "30%", icon: "📦" },
			{ key: "quantity", label: "Quantity", width: "10%", icon: "🔢" },
			{ key: "price", label: "Price", width: "20%", icon: "💲" },
		];

		const formatValue = (value, prop) => {
			if (value === null || value === undefined) return "—";

			if (prop.key === "startTime" || prop.key === "endTime") {
				return moment(value).format("MM/DD HH:mm");
			}

			return value;
		};

		let tableHTML = `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Product Usage Report 📦")}

        <table style="width: 100%; table-layout: fixed; border-collapse: collapse; border-spacing: 0; margin-top: 0px; font-size: 7pt; background-color: #fff; border-radius: 0px; overflow: hidden; border: 1px solid #e2e8f0;">
          <thead>
            <tr style="background: linear-gradient(to right, #f8f9fa, #ffffff);">`;

		properties.forEach((prop) => {
			tableHTML += `
        <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; width: ${prop.width}; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: #2d3748;">
          <span style="display: inline-block; margin-right: 2px;">${prop.icon}</span>
          ${prop.label}
        </th>`;
		});

		tableHTML += `</tr></thead><tbody>`;

		productUsages.forEach((productUsage, index) => {
			tableHTML += `<tr style="background-color: ${index % 2 === 1 ? "#f8fafc" : "#fff"};">`;

			properties.forEach((prop) => {
				const value = formatValue(productUsage[prop.key], prop);
				tableHTML += `
          <td style="padding: 3px 4px; border-bottom: 1px solid #e2e8f0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; line-height: 1.2; color: #4a5568;">${value}</td>`;
			});
			tableHTML += `</tr>`;
		});

		tableHTML += `
          </tbody>
        </table>
        ${generateCommonFooter()}
      </div>`;
		return tableHTML;
	};

	// Medication Administrations
	// Medication Administrations
	const generateMedicationAdministrationPdf = (medicationAdministration) => {
		if (!medicationAdministration) return null;
		const documentId = `MA-${medicationAdministration.id}`;

		return `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Medication Administration Details 💉", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Administration Time: ⏰</strong> ${
				medicationAdministration.administrationTime ? moment(medicationAdministration.administrationTime).format("YYYY-MM-DD HH:mm") : "N/A"
			}</p>
          <p><strong>Amount: 📏</strong> ${medicationAdministration.amount || "N/A"}</p>
          <p><strong>Calculated Price: 💲</strong> ${medicationAdministration.calculatedPrice || "N/A"}</p>
          <p><strong>Prescribed Medication Name: 💊</strong> ${medicationAdministration.medicationName || "N/A"}</p>
        </div>
        ${generateCommonFooter()}
      </div>`;
	};

	const generateMedicationAdministrationTablePdf = (medicationAdministrations) => {
		//removed , columns
		if (!medicationAdministrations || medicationAdministrations.length === 0)
			return '<p style="text-align: center; color: #666;">No medication administration data available.</p>';

		const properties = [
			{
				key: "administrationTime",
				label: "Admin. Time",
				width: "30%",
				icon: "⏰",
				format: (value) => (value ? moment(value).format("YYYY-MM-DD HH:mm") : "—"),
			},
			{ key: "amount", label: "Amount", width: "20%", icon: "📏" },
			{ key: "calculatedPrice", label: "Price", width: "20%", icon: "💲" },
			{ key: "medicationName", label: "Medication", width: "30%", icon: "💊" },
		];

		const formatValue = (value, prop) => {
			if (value === null || value === undefined) return "—";
			if (prop.format) return prop.format(value);
			return value;
		};

		let tableHTML = `
        <div style="${commonPdfStyles}">
          ${generateCommonHeader("Medication Administrations 💉")}

          <table style="width: 100%; table-layout: fixed; border-collapse: collapse; border-spacing: 0; margin-top: 0px; font-size: 7pt; background-color: #fff; border-radius: 0px; overflow: hidden; border: 1px solid #e2e8f0;">
            <thead>
              <tr style="background: linear-gradient(to right, #f8f9fa, #ffffff);">`;

		properties.forEach((prop) => {
			tableHTML += `
          <th style="padding: 3px 4px; text-align: left; border-bottom: 1px solid #e2e8f0; font-weight: 500; width: ${prop.width}; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: #2d3748;">
            <span style="display: inline-block; margin-right: 2px;">${prop.icon}</span>
            ${prop.label}
          </th>`;
		});

		tableHTML += `</tr></thead><tbody>`;

		medicationAdministrations.forEach((medication, index) => {
			tableHTML += `<tr style="background-color: ${index % 2 === 1 ? "#f8fafc" : "#fff"};">`;

			properties.forEach((prop) => {
				const value = formatValue(medication[prop.key], prop);
				tableHTML += `
            <td style="padding: 3px 4px; border-bottom: 1px solid #e2e8f0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; line-height: 1.2; color: #4a5568;">${value}</td>`;
			});
			tableHTML += `</tr>`;
		});

		tableHTML += `
            </tbody>
          </table>
          ${generateCommonFooter()}
        </div>`;
		return tableHTML;
	};

	// Image Reports
	const generateImageReportTablePdf = async (imageReports) => {
		if (!imageReports || imageReports.length === 0) {
			return "<p>No image report data available.</p>";
		}

		let combinedContent = "";
		for (let i = 0; i < imageReports.length; i++) {
			// Use a standard for loop
			let reportContent = await generateImageReportPdf(imageReports[i]);
			if (reportContent) {
				// Add page break *before* each report EXCEPT the first one.
				if (i > 0) {
					combinedContent += `<div style="page-break-before: always;">${reportContent}</div>`;
				} else {
					combinedContent += `<div>${reportContent}</div>`; // No page break for the first item
				}
			}
		}
		return combinedContent;
	};

	const generateImageReportPdf = async (imageReport) => {
		if (!imageReport) {
			notification.error({ message: "Error", description: "No image report data available." });
			return null;
		}
		const documentId = `IR-${imageReport.id}`;

		let htmlContent = `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Image Report Details 🖼️", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Report Date: 📅</strong> ${
				imageReport.reportDateTime ? moment(imageReport.reportDateTime).format("YYYY-MM-DD HH:mm") : "N/A"
			}</p>
          <p><strong>Image Type: 📷</strong> ${imageReport.imageType || "N/A"}</p>
          <p><strong>Description: 📝</strong> ${imageReport.description || "N/A"}</p>
          <p><strong>Report Text: 📃</strong> ${imageReport.reportText || "N/A"}</p>
          <div style="margin-top: 20px;">
    `;

		if (imageReport.imageUrls && imageReport.imageUrls.length > 0) {
			for (const fullUrl of imageReport.imageUrls) {
				const isVideo = [".mp4", ".webm", ".ogg"].some((ext) => fullUrl.toLowerCase().endsWith(ext));
				if (isVideo) {
					const qrCodeDataURL = await QRCode.toDataURL(fullUrl);
					htmlContent += `
            <div style="margin-bottom: 10px; text-align: center;">
              <p><strong>Video QR Code:</strong></p>
              <img src="${qrCodeDataURL}" alt="QR Code for ${fullUrl}" style="width: 150px; height: 150px;"/>
              <p style="font-size: 10px; color: #666;">Scan the QR code to view the video.</p> 
            </div>`; //Removed direct link display
				} else {
					const base64Data = await toBase64(fullUrl);
					if (base64Data) {
						htmlContent += `
                        <div style="margin-bottom: 10px; text-align: center;">
                          <img src="${base64Data}" alt="Image ${fullUrl}" style="width: 100%; object-fit: contain;"/>
                        </div>`; //Key change is here
					} else {
						htmlContent += `<p>Failed to load image: ${fullUrl}</p>`;
					}
				}
			}
		} else {
			htmlContent += `<p>No images or videos available.</p>`;
		}

		htmlContent += `
          </div>
        </div>
        ${generateCommonFooter()}
      </div>`;
		return htmlContent;
	};

	// Lab Results
	const generateResultTable = (structureMapTable, resultMap) => {
		if (!structureMapTable || !resultMap) {
			return { columns: [], dataSource: [] };
		}

		const { headers, rows: structureRows } = structureMapTable;

		const columns = headers.map((header) => ({
			title: header,
			dataIndex: header,
			key: header,
		}));

		const dataSource = structureRows.map((structRow) => {
			const rowKey = structRow[0]; // First element is the key
			const rowData = resultMap[rowKey] || {};
			const row = { key: rowKey };

			headers.forEach((header, index) => {
				const initialValue = rowData?.[header] != null ? rowData[header] : structRow[index] != null ? structRow[index] : null;
				row[header] = initialValue;
			});

			return row;
		});

		return { columns, dataSource };
	};

	const generateLabResultPdf = async (labResult, labTests) => {
		if (!labResult || !labTests) {
			notification.error({ message: "Error", description: "No lab result or test details available." });
			return null;
		}

		const labTestDetails = labTests.find((test) => test.id === labResult.labTestId);
		if (!labTestDetails) {
			notification.error({ message: "Error", description: "Lab test details not found." });
			return null;
		}

		const { testName, description } = labTestDetails;
		const { resultDateTime, notes, resultMap } = labResult;
		const { columns, dataSource } = generateResultTable(labTestDetails.structureMap?.table, resultMap);
		const documentId = `LR-${labResult.id}`;

		const htmlContent = `
      <div style="${commonPdfStyles}">
        ${generateCommonHeader("Lab Result Details 🧪", documentId)}
        <div style="padding: 0 0.5rem;">
          <p><strong>Test Name: 🔬</strong> ${testName || "Not Available"}</p>
          <p><strong>Test Description: 📝</strong> ${description || "Not Available"}</p>
          <p><strong>Result Date: 📅</strong> ${resultDateTime ? moment(resultDateTime).format("YYYY-MM-DD HH:mm") : "Not Available"}</p>
          <p><strong>Notes: 🗒️</strong> ${notes || "Not Available"}</p>
          ${generateTableHTML(columns, dataSource)}
        </div>
        ${generateCommonFooter()}
      </div>`;

		return htmlContent;
	};

	const generateLabResultTablePdf = async (labResults, labTests) => {
		if (!labResults || labResults.length === 0 || !labTests) {
			return "<p>No lab results available.</p>";
		}

		let combinedContent = "";
		for (const labResult of labResults) {
			let resultContent = await generateLabResultPdf(labResult, labTests);
			if (resultContent) {
				combinedContent += `<div style="page-break-after: always;">${resultContent}</div>`;
			}
		}

		return combinedContent; // Return ONLY the combined content, no wrapper
	};

	// --- NEW: Patient File Generation ---
	const generatePatientFilePdf = async (patient, allData) => {
		if (!patient) {
			notification.error({ message: "Error", description: "No patient data available." });
			return null;
		}

		const {
			admissions,
			appointments,
			assessments,
			billings,
			carePlans,
			prescriptions,
			vitalSigns,
			productUsages,
			medicationAdministrations,
			imageReports,
			labResults,
			documents,
		} = allData;

		let profilePictureBase64 = null;
		if (patient.profilePictureURL) {
			profilePictureBase64 = await toBase64(generateImageUrl(patient.profilePictureURL)); // Implement or import toBase64
			if (!profilePictureBase64) {
				console.error("Failed to load profile picture.");
				// You might choose to proceed without the image or show a placeholder
			}
		}

		let htmlContent = `
        <div style="${commonPdfStyles}">
          <!-- Cover Page -->
            <div style="text-align: center; padding: 20px; background-color: #f0f2f5;">
              ${
					profilePictureBase64
						? `<img src="${profilePictureBase64}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover; margin-bottom: 10px;" alt="Patient Profile">`
						: `<div style="width: 100px; height: 100px; border-radius: 50%; background-color: #ddd; margin: 0 auto 10px;"></div>` /* Placeholder */
				}
               <h1 style="margin: 0; font-size: 24px; color: #333;">${patient.firstName} ${patient.lastName}</h1>
               <p style="margin: 5px 0; font-size: 16px; color: #666;">MRN: ${patient.medicalRecordNumber}</p>
               <p style="margin: 5px 0; font-size: 16px; color: #666;">DOB: ${moment(patient.dateOfBirth).format("YYYY-MM-DD")}</p>
               <p style="margin: 5px 0; font-size: 16px; color: #666;">Gender: ${patient.gender}</p>
               <p style="margin: 5px 0; font-size: 16px; color: #666;">Blood Type: ${patient.bloodType}</p>
            </div>
          
          <div style="page-break-after: always;"></div>
          <!-- End Cover Page -->
    `;

		// Add each section with a page break before (except the first)
		if (admissions && admissions.length > 0) {
			htmlContent += generateAdmissionTablePdf(admissions, columns); // Assuming you have columns defined
		}
		if (appointments && appointments.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateAppointmentTablePdf(appointments, columns)}</div>`;
		}
		if (assessments && assessments.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateAssessmentTablePdf(assessments)}</div>`;
		}
		if (billings && billings.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateBillingTablePdf(billings)}</div>`;
		}
		if (carePlans && carePlans.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateCarePlanTablePdf(carePlans, columns)}</div>`;
		}
		if (prescriptions && prescriptions.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generatePrescriptionTablePdf(prescriptions)}</div>`;
		}
		if (vitalSigns && vitalSigns.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateVitalSignTablePdf(vitalSigns)}</div>`;
		}
		if (productUsages && productUsages.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateProductUsageTablePdf(productUsages)}</div>`;
		}
		if (medicationAdministrations && medicationAdministrations.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${generateMedicationAdministrationTablePdf(medicationAdministrations)}</div>`;
		}
		if (imageReports && imageReports.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${await generateImageReportTablePdf(imageReports)}</div>`;
		}
		if (labResults && labResults.length > 0) {
			htmlContent += `<div style="page-break-before: always;">${await generateLabResultTablePdf(labResults, labTests)}</div>`;
		}

		htmlContent += `</div>`; // Close the main container
		return htmlContent;
	};

	// --- Main PDF Generation Function ---
	const generatePdf = async () => {
		let htmlContent;
		let filename;
		let orientation = "portrait"; // Default orientation

		// Get all data from the usePatientDetailStore hook
		const {
			patient,
			admissions,
			appointments,
			assessments,
			billings,
			carePlans,
			prescriptions,
			vitalSigns,
			productUsages,
			medicationAdministrations,
			imageReports,
			labResults,
			documents,
		} = usePatientDetailStore.getState(); // Use getState() to access the store's state

		const allData = {
			admissions,
			appointments,
			assessments,
			billings,
			carePlans,
			prescriptions,
			vitalSigns,
			productUsages,
			medicationAdministrations,
			imageReports,
			labResults,
			documents,
		};

		try {
			if (mode === "single") {
				switch (type) {
					case "admission":
						htmlContent = generateAdmissionPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "appointment":
						htmlContent = generateAppointmentPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "billing":
						htmlContent = await generateBillingPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYY-MM-DD_HH-mm-ss")}.pdf`;
						break;
					case "assessment":
						htmlContent = generateAssessmentPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "carePlan":
						htmlContent = generateCarePlanPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "prescription":
						htmlContent = generatePrescriptionPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "vitalSign":
						htmlContent = generateVitalSignPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						orientation = "landscape"; // Vital Signs is landscape
						break;
					case "productUsage":
						htmlContent = generateProductUsagePdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "medicationAdministration":
						htmlContent = generateMedicationAdministrationPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "imageReport":
						htmlContent = await generateImageReportPdf(data);
						filename = `${fileNamePrefix}_${data.id}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "labResult":
						htmlContent = await generateLabResultPdf(data, labTests);
						filename = `${fileNamePrefix}_${moment().format("YYYYMMDD_HHmm")}.pdf`;
						break;

					default:
						notification.error({ message: "Error", description: "Invalid PDF type." });
						return;
				}
			} else if (mode === "table") {
				switch (type) {
					case "admission":
						htmlContent = generateAdmissionTablePdf(data, columns);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "appointment":
						htmlContent = generateAppointmentTablePdf(data, columns);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "billing":
						htmlContent = generateBillingTablePdf(data);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "assessment":
						htmlContent = generateAssessmentTablePdf(data);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "carePlan":
						htmlContent = generateCarePlanTablePdf(data, columns);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "prescription":
						htmlContent = generatePrescriptionTablePdf(data, columns);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "vitalSign":
						htmlContent = generateVitalSignTablePdf(data); //Removed , columns
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						orientation = "landscape"; // Vital Signs Table is landscape
						break;
					case "productUsage":
						htmlContent = generateProductUsageTablePdf(data); // Removed , columns
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "medicationAdministration":
						htmlContent = generateMedicationAdministrationTablePdf(data, columns);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "imageReport":
						htmlContent = await generateImageReportTablePdf(data);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;
					case "labResult":
						htmlContent = await generateLabResultTablePdf(data, labTests);
						filename = `${fileNamePrefix}_table_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
						break;

					default:
						notification.error({ message: "Error", description: "Invalid PDF type." });
						return;
				}
			} else if (mode === "patientFile") {
				if (!patient) {
					notification.error({ message: "Error", description: "Patient data is not available." });
					return;
				}
				htmlContent = await generatePatientFilePdf(patient, allData);
				filename = `patient_file_${patient.medicalRecordNumber}_${moment().format("YYYYMMDD_HHmmss")}.pdf`;
			} else {
				notification.error({ message: "Error", description: "Invalid PDF mode." });
				return;
			}

			if (!htmlContent) {
				notification.info({ message: "Info", description: "No data to export." });
				return;
			}

			const options = {
				margin: 0,
				filename: filename,
				image: { type: "jpeg", quality: 1 },
				html2canvas: { scale: 4, useCORS: true },
				jsPDF: {
					unit: "mm",
					format: "a4",
					orientation: orientation, // Use the determined orientation
				},
			};

			await html2pdf().from(htmlContent).set(options).save();
			notification.success({ message: "Success", description: "PDF generated successfully!" });
		} catch (error) {
			console.error("Error generating PDF:", error);
			notification.error({ message: "Error", description: `Failed to generate PDF: ${error.message}` });
		}
	};
	const generateImageUrl = (url) => {
		if (!url) return null;

		const processedUrl = `${
			(url.startsWith("./") ? url.substring(1) : url).startsWith("/")
				? url.startsWith("./")
					? url.substring(1)
					: url
				: "/" + (url.startsWith("./") ? url.substring(1) : url)
		}`;

		return `${processedUrl}`;
	};

	return <div onClick={generatePdf}>{children}</div>;
};

export default PdfGenerator;
