package mine.profile.website.models;

public enum ActivityType {
    VITAL_SIGNS_RECORDED,
    MEDICATION_ADMINISTERED,
    ASSESSMENT_COMPLETED,
    CARE_PLAN_UPDATED,
    ADMISSION_RECORDED,
    DISCHARGE_RECORDED,
    ROOM_ASSIGNMENT_UPDATED,
    UNIT_ASSIGNMENT_UPDATED,
    OTHER
}