# # =---=-------------production configs=-===================----------------------==========================
spring.application.name=website
spring.datasource.url=jdbc:postgresql://database:5432/mydb
spring.datasource.username=bassel
spring.datasource.password=fl studio
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Schema Configuration
spring.jpa.properties.hibernate.default_schema=public

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Server Error Handling
server.error.include-message=always
server.error.include-binding-errors=always


# Multipart Properties
spring.servlet.multipart.enabled=true


# JWT Configuration
jwt.secret=c2VjcmV0X2Zvcl90ZXN0aW5nX29ubHlfZG9fbm90X3VzZV9pdF9pbl9wcm9kdWN0aW9uXzE2MzYxODcwNzY=
jwt.expiration=86400000


jwt.cookie.name=jwt-token

logging.level.org.springframework.security=DEBUG
logging.level.mine.profile.website=DEBUG

# New property for the upload directory
file.upload.dir=/api/uploads
gemini.api.key=AIzaSyCws6pXyzrRIQPYXl9TW-sd1xV2CBP05W4



spring.servlet.multipart.max-file-size=1000 MB
spring.servlet.multipart.max-request-size=1000 MB
# =---=-------------deverlopment configs(runs the server on port 8080 by default)=-===================----------------------========================
# spring.application.name=website
# spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
# spring.datasource.username=bassel
# spring.datasource.password=fl studio
# spring.datasource.driver-class-name=org.postgresql.Driver


# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# # Schema Configuration
# spring.jpa.properties.hibernate.default_schema=public

# # Logging Configuration
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# # Server Error Handling
# server.error.include-message=always
# server.error.include-binding-errors=always

# logging.level.mine.profile.website.services=INFO
# # Multipart Properties
# spring.servlet.multipart.enabled=true


# # JWT Configuration
# jwt.secret=c2VjcmV0X2Zvcl90ZXN0aW5nX29ubHlfZG9fbm90X3VzZV9pdF9pbl9wcm9kdWN0aW9uXzE2MzYxODcwNzY=

# jwt.expiration=86400000

# jwt.cookie.name=jwt-token

# logging.level.org.springframework.security=DEBUG
# logging.level.mine.profile.website=DEBUG

# # New property for the upload directory
# file.upload.dir=./api/uploads

# HOSTEDON=http://localhost:8080


# #the filehandler path for saving files.
# file.upload.directory=./api/uploads
# gemini.api.key=AIzaSyCws6pXyzrRIQPYXl9TW-sd1xV2CBP05W4


# spring.servlet.multipart.max-file-size=1000 MB
# spring.servlet.multipart.max-request-size=1000 MB
